# Generated by Django 2.1.7 on 2019-02-20 02:59

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import mastermind.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('R', 'Red'), ('O', 'Orange'), ('Y', 'Yellow'), ('G', 'Green'), ('B', 'Blue'), ('P', 'Purple')], max_length=1), size=4)),
                ('number', models.PositiveIntegerField(blank=True)),
                ('winner', models.CharField(choices=[('B', 'Breaker'), ('M', 'Maker'), ('', '')], max_length=1)),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_board', models.PositiveIntegerField(validators=[mastermind.validators.validate_even_boards])),
                ('board_size', models.PositiveIntegerField(default=12)),
                ('breaker_score', models.PositiveIntegerField(default=0)),
                ('maker_score', models.PositiveIntegerField(default=0)),
                ('codebreaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('R', 'Red'), ('O', 'Orange'), ('Y', 'Yellow'), ('G', 'Green'), ('B', 'Blue'), ('P', 'Purple')], max_length=1), size=4)),
                ('number', models.PositiveIntegerField(blank=True)),
                ('feedback', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('F', 'Full'), ('C', 'Color'), ('', '')], max_length=1), blank=True, size=4)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastermind.Board')),
            ],
            options={
                'db_table': 'guess',
            },
        ),
        migrations.AddField(
            model_name='board',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastermind.Game'),
        ),
        migrations.AddIndex(
            model_name='guess',
            index=models.Index(fields=['board', 'number'], name='guess_board_i_d4ca1f_idx'),
        ),
    ]
